<?php

namespace App\Controller;

use App\Entity\Room;
use App\Repository\RoomRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Validator\Validator\ValidatorInterface;

/**
 * @Route("/api/room")
 */
class RoomController extends AbstractController
{
    /**
     * Create room
     * Only user who has ROLE_GUIDE as role can access.
     * @param Request
     * @param ValidatorInterface
     * @return jsonArray[]
     * @Route("/create", name="room_create", methods={"POST"})
     */
    public function roomCreate(Request $request, ValidatorInterface $validator)
    {
        $em = $this->getDoctrine()->getManager();

        if(!$this->isGranted('ROLE_GUIDE'))
        {
            $responseArray['code'] = 403;
            $responseArray['message'] = 'Only ROLE_GUIDE can access this function';

            return new JsonResponse($responseArray);
        }

        $owner = $this->getUser();

        $name = $request->request->get('name');
        $description = $request->request->get('description');
        $qr_url = 'http://localhost:8000';      // the QR URL is generated by QR code.
        $start_time = new \DateTime();          // this file can get from Front-End.

        $room = new Room($owner, $name, $description, $qr_url, $start_time);
        
        $errors = $validator->validate($room);
        if(count($errors) > 0)
        {
            foreach($errors as $error)
            {
                $key = $error->getPropertyPath();
                $responseArray['code'] = $error->getCode();
                $responseArray[$key] = $error->getMessage();
            }
            return new JsonResponse($responseArray);
        }

        $em->persist($room);
        $em->flush();

        return new JsonResponse('Successfully');
    }

    /**
     * Delete room
     * Only owner can access to delete room.
     * @param int $room_id
     * @param RoomRepository
     * @return jsonArray[]
     * @Route("/{room_id}/delete", name="room_delete", methods={"POST"})
     */
    public function roomDelete(int $room_id, RoomRepository $roomRepository)
    {
        $em = $this->getDoctrine()->getManager();

        $room = $roomRepository->find($room_id);
        if(!$room)
        {
            $responseArray['code'] = 400;
            $responseArray['message'] = 'The room is already not existed.';
            return new JsonResponse($responseArray);
        }

        if($this->getUser() != $room->getOwner())       // Only owner can delete the room.
        {
            $responseArray['code'] = 401;
            $responseArray['message'] = "You can not delete this room because of not owner.";
            return new JsonResponse($responseArray);
        }

        $em->remove($room);
        $em->flush();

        return new JsonResponse('Successfully');
    }
}
