user_register:
    path: /user/register
    controller: App\Controller\UserController::userRegister
    methods: POST

login_check:
    path: /login_check
    methods: [POST]

room_list:
    path: /room/list
    controller: App\Controller\RoomController::roomList

room_create:
    path: /room/create
    controller: App\Controller\RoomController::roomCreate

room_delete:
    path: /room/{id}/delete
    controller: App\Controller\RoomController::roomDelete

audio_create:
    path: /audio/create
    controller: App\Controller\AudioController:audioCreate

message_create:
    path: /message/create
    controller: App\Controller\MessageController:messageCreate

api:
    path: /api
    controller: App\Controller\DefaultController::api





